/* =======================================================
   Globals & State
   ======================================================= */

var images = [];      // Extracted images
var currentIndex = 0; // Current selection index
var zoom = 1;         // Current zoom level
var viewMode = 1;     // 1: Single, 2: Dual
var sortMode = 'latest'; // Sort option
var mediaFilter = 'all'; // all | image | video
var sortedImageOrder = []; // Raw image indexes in sidebar display order
var orientation = 'horz'; // horz: Slide, vert: Scroll
var deletedImages = [];  // Deleted images stack for restoration
var navStep = 1;         // Navigation step (1 or 2 pages)

// DOM Cache
var dom = {
    btnOpen: document.getElementById("btnOpen"),
    btnFileMenu: document.getElementById("btnFileMenu"),
    fileMenuDropdown: document.getElementById("fileMenuDropdown"),
    btnSaveDbMenu: document.getElementById("btnSaveDbMenu"),
    saveDbDropdown: document.getElementById("saveDbDropdown"),
    btnSaveDbSnapshot: document.getElementById("btnSaveDbSnapshot"),
    btnOpenDbHistory: document.getElementById("btnOpenDbHistory"),
    dbHistoryModal: document.getElementById("dbHistoryModal"),
    dbHistoryFrame: document.getElementById("dbHistoryFrame"),
    btnCloseDbHistoryModal: document.getElementById("btnCloseDbHistoryModal"),
    importSection: document.getElementById("importSection"),
    importPanelContent: document.getElementById("importPanelContent"),
    btnToggleImportPanel: document.getElementById("btnToggleImportPanel"),
    dropzone: document.getElementById("dropzone"),
    dropzoneImg: document.getElementById("dropzoneImg"),
    input: document.getElementById("fileInput"),
    gallery: document.getElementById("gallery"),
    previewContainer: document.getElementById("previewContainer"),
    preview: document.getElementById("preview"),
    preview2: document.getElementById("preview2"),
    zoomInfo: document.getElementById("zoomInfo"),
    previewWrap: document.querySelector(".previewWrap"),
    btnViewModeCycle: document.getElementById("btnViewModeCycle"),
    btnGridCycle: document.getElementById("btnGridCycle"),
    sortSelect: document.getElementById("sortSelect"),
    mediaFilterSelect: document.getElementById("mediaFilterSelect"),
    btnToggleFavs: document.getElementById("btnToggleFavs"),
    favSidebar: document.getElementById("favSidebar"),
    favList: document.getElementById("favList"),
    imageMetadataModal: document.getElementById("imageMetadataModal"),
    btnMetadataClose: document.getElementById("btnMetadataClose"),
    btnMetadataCancel: document.getElementById("btnMetadataCancel"),
    btnMetadataSave: document.getElementById("btnMetadataSave"),
    btnAddMetadataField: document.getElementById("btnAddMetadataField"),
    metadataTechnicalGrid: document.getElementById("metadataTechnicalGrid"),
    metadataPath: document.getElementById("metadataPath"),
    metadataGroup: document.getElementById("metadataGroup"),
    metadataCreatedAt: document.getElementById("metadataCreatedAt"),
    metadataTitleField: document.getElementById("metadataTitleField"),
    metadataAuthor: document.getElementById("metadataAuthor"),
    metadataCopyright: document.getElementById("metadataCopyright"),
    metadataKeywords: document.getElementById("metadataKeywords"),
    metadataDescription: document.getElementById("metadataDescription"),
    metadataCustomFields: document.getElementById("metadataCustomFields"),
    embeddedMetadataView: document.getElementById("embeddedMetadataView"),
    btnOrientation: document.getElementById("btnOrientationTop"),
    placeholder: document.getElementById("placeholder"),
    previewMeta: document.getElementById("previewMeta"),
    metaDynamicArea: document.getElementById("metaDynamicArea"),
    btnTogglePreviewMenu: document.getElementById("btnTogglePreviewMenu"),
    btnFullscreen: document.getElementById("btnFullscreen"),
    btnCenterPreview: document.getElementById("btnCenterPreview"),
    btnResetZoom: document.getElementById("btnResetZoom"),
    btnAddImg: document.getElementById("btnAddImg"),
    btnOpenFolder: document.getElementById("btnOpenFolder"),
    btnSettings: document.getElementById("btnSettings"),
    btnThemeToggle: document.getElementById("btnThemeToggle"),
    themeToggleIcon: document.getElementById("themeToggleIcon"),
    addImgInput: document.getElementById("addImgInput"),
    zipImgInput: document.getElementById("zipImgInput"),
    folderImgInput: document.getElementById("folderImgInput"),
    btnImportImages: document.getElementById("btnImportImages"),
    btnImportZip: document.getElementById("btnImportZip"),
    btnImportFolder: document.getElementById("btnImportFolder"),
    btnPasteImg: document.getElementById("btnPasteImg"),
    importStatus: document.getElementById("importStatus"),
    btnSave: document.getElementById("btnSave"),
    btnSaveCompact: document.getElementById("btnSaveCompact"),
    btnSaveFmaPanel: document.getElementById("btnSaveFmaPanel"),
    btnClear: document.getElementById("btnClear"),
    btnZoomIn: document.getElementById("btnZoomIn"),
    btnZoomOut: document.getElementById("btnZoomOut"),
    zoomText: document.getElementById("zoomText"),
    previewBottomControls: document.getElementById("previewBottomControls"),
    btnRestoreRemove: document.getElementById("btnRestoreRemove"),
    btnRestore: document.getElementById("btnRestore"),
    imageCount: document.getElementById("imageCount"),
    resizer: document.getElementById("resizer"),
    leftPanel: document.getElementById("leftPanel"),
    btnStepCycle: document.getElementById("btnStepCycle"),
    btnZip: document.getElementById("btnZip"),
    btnPrev: document.getElementById("btnPrev"),
    btnNext: document.getElementById("btnNext"),
    btnPrevMenu: document.getElementById("btnPrevMenu"),
    btnNextMenu: document.getElementById("btnNextMenu"),
    pageText: document.getElementById("pageText"),
    navMenu: document.getElementById("navMenu"),
    loadingOverlay: document.getElementById("loadingOverlay"),
    loadingTitle: document.getElementById("loadingTitle"),
    progressBar: document.getElementById("progressBar"),
    progressPercent: document.getElementById("progressPercent"),
    backgroundImportProgress: document.getElementById("backgroundImportProgress"),
    backgroundImportTitle: document.getElementById("backgroundImportTitle"),
    backgroundImportBar: document.getElementById("backgroundImportBar"),
    backgroundImportPercent: document.getElementById("backgroundImportPercent"),
    cropModal: document.getElementById("cropModal"),
    cropCanvas: document.getElementById("cropCanvas"),
    cropSelectionInfo: document.getElementById("cropSelectionInfo"),
    cropWidthInput: document.getElementById("cropWidthInput"),
    cropHeightInput: document.getElementById("cropHeightInput"),
    cropAspectLock: document.getElementById("cropAspectLock"),
    btnApplyCropSize: document.getElementById("btnApplyCropSize"),
    btnCropClose: document.getElementById("btnCropClose"),
    btnCropCancel: document.getElementById("btnCropCancel"),
    btnCropReset: document.getElementById("btnCropReset"),
    btnCropCreate: document.getElementById("btnCropCreate"),
    cropSaveChoice: document.getElementById("cropSaveChoice"),
    cropResultPreview: document.getElementById("cropResultPreview"),
    cropResultDimensions: document.getElementById("cropResultDimensions"),
    btnCropChoiceCancel: document.getElementById("btnCropChoiceCancel"),
    btnCropReplace: document.getElementById("btnCropReplace"),
    btnCropNew: document.getElementById("btnCropNew"),
    settingsModal: document.getElementById("settingsModal"),
    btnSettingsClose: document.getElementById("btnSettingsClose"),
    btnSettingsCancel: document.getElementById("btnSettingsCancel"),
    btnSettingsSave: document.getElementById("btnSettingsSave"),
    btnClearApiKey: document.getElementById("btnClearApiKey"),
    btnToggleApiKey: document.getElementById("btnToggleApiKey"),
    aiStudioApiKey: document.getElementById("aiStudioApiKey"),
    btnApplySharedApiKey: document.getElementById("btnApplySharedApiKey"),
    btnToggleAiKeyUsage: document.getElementById("btnToggleAiKeyUsage"),
    sharedApiKeyStatus: document.getElementById("sharedApiKeyStatus"),
    enableAiUpscale: document.getElementById("enableAiUpscale"),
    enableAiBgRemove: document.getElementById("enableAiBgRemove"),
    enableStoryApp: document.getElementById("enableStoryApp"),
    enableStoryHtmlApp: document.getElementById("enableStoryHtmlApp"),
    enableAuraApp: document.getElementById("enableAuraApp"),
    enableAuraGeminiApp: document.getElementById("enableAuraGeminiApp"),
    enableBackgroundGeminiApp: document.getElementById("enableBackgroundGeminiApp"),
    enableGeminiApp: document.getElementById("enableGeminiApp"),
    enableBgRemoverApp: document.getElementById("enableBgRemoverApp"),
    aiUpscaleResolution: document.getElementById("aiUpscaleResolution"),
    upscaleModal: document.getElementById("upscaleModal"),
    upscaleTitle: document.getElementById("upscaleTitle"),
    upscaleSubtitle: document.getElementById("upscaleSubtitle"),
    upscalePreview: document.getElementById("upscalePreview"),
    upscaleDimensionInfo: document.getElementById("upscaleDimensionInfo"),
    localUpscaleControls: document.getElementById("localUpscaleControls"),
    aiUpscaleControls: document.getElementById("aiUpscaleControls"),
    aiResolutionText: document.getElementById("aiResolutionText"),
    aiUpscalePrompt: document.getElementById("aiUpscalePrompt"),
    btnResetAiUpscalePrompt: document.getElementById("btnResetAiUpscalePrompt"),
    upscaleTargetWidth: document.getElementById("upscaleTargetWidth"),
    upscaleTargetHeight: document.getElementById("upscaleTargetHeight"),
    upscaleAspectLock: document.getElementById("upscaleAspectLock"),
    sharpenAmount: document.getElementById("sharpenAmount"),
    sharpenValue: document.getElementById("sharpenValue"),
    upscaleModeLabel: document.getElementById("upscaleModeLabel"),
    btnUpscaleClose: document.getElementById("btnUpscaleClose"),
    btnUpscaleCancel: document.getElementById("btnUpscaleCancel"),
    btnRunUpscale: document.getElementById("btnRunUpscale"),
    upscaleSaveChoice: document.getElementById("upscaleSaveChoice"),
    btnUpscaleChoiceCancel: document.getElementById("btnUpscaleChoiceCancel"),
    btnUpscaleReplace: document.getElementById("btnUpscaleReplace"),
    btnUpscaleNew: document.getElementById("btnUpscaleNew"),
    bgRemoveModal: document.getElementById("bgRemoveModal"),
    bgRemoveTitle: document.getElementById("bgRemoveTitle"),
    bgRemoveSubtitle: document.getElementById("bgRemoveSubtitle"),
    bgRemovePreview: document.getElementById("bgRemovePreview"),
    bgRemoveModeBadge: document.getElementById("bgRemoveModeBadge"),
    localBgRemoveInfo: document.getElementById("localBgRemoveInfo"),
    aiBgRemoveInfo: document.getElementById("aiBgRemoveInfo"),
    aiBgRemovePrompt: document.getElementById("aiBgRemovePrompt"),
    btnResetAiBgPrompt: document.getElementById("btnResetAiBgPrompt"),
    bgRemoveProgressBar: document.getElementById("bgRemoveProgressBar"),
    bgRemoveStatus: document.getElementById("bgRemoveStatus"),
    bgRemovePercent: document.getElementById("bgRemovePercent"),
    bgRemoveFooterText: document.getElementById("bgRemoveFooterText"),
    btnBgRemoveClose: document.getElementById("btnBgRemoveClose"),
    btnBgRemoveCancel: document.getElementById("btnBgRemoveCancel"),
    btnBgRemoveAddGallery: document.getElementById("btnBgRemoveAddGallery"),
    btnBgRemoveRefine: document.getElementById("btnBgRemoveRefine"),
    btnRunBgRemove: document.getElementById("btnRunBgRemove"),
    btnBgEngineWebgl: document.getElementById("btnBgEngineWebgl"),
    btnBgEngineOnnx: document.getElementById("btnBgEngineOnnx"),
    webglBgRemoveInfo: document.getElementById("webglBgRemoveInfo"),
    onnxBgRemoveSettings: document.getElementById("onnxBgRemoveSettings"),
    bgBoundaryStrength: document.getElementById("bgBoundaryStrength"),
    bgBoundaryStrengthValue: document.getElementById("bgBoundaryStrengthValue"),
    bgCustomBackgroundEnabled: document.getElementById("bgCustomBackgroundEnabled"),
    bgCustomBackgroundColor: document.getElementById("bgCustomBackgroundColor"),
    bgCustomBackgroundColorValue: document.getElementById("bgCustomBackgroundColorValue"),
    btnPrepareBgModel: document.getElementById("btnPrepareBgModel"),
    btnSelectBgModel: document.getElementById("btnSelectBgModel"),
    bgModelFileInput: document.getElementById("bgModelFileInput"),
    bgModelLocation: document.getElementById("bgModelLocation"),
    bgRemoveSaveChoice: document.getElementById("bgRemoveSaveChoice"),
    btnBgRemoveChoiceCancel: document.getElementById("btnBgRemoveChoiceCancel"),
    btnBgRemoveReplace: document.getElementById("btnBgRemoveReplace"),
    btnBgRemoveNew: document.getElementById("btnBgRemoveNew"),
    bgMaskEditorModal: document.getElementById("bgMaskEditorModal"),
    bgMaskEditorDialog: document.getElementById("bgMaskEditorDialog"),
    btnMaskEditorClose: document.getElementById("btnMaskEditorClose"),
    btnMaskEditorFit: document.getElementById("btnMaskEditorFit"),
    btnMaskEditorFullscreen: document.getElementById("btnMaskEditorFullscreen"),
    maskEditorZoomText: document.getElementById("maskEditorZoomText"),
    maskEditorStage: document.getElementById("maskEditorStage"),
    maskEditorCanvasStack: document.getElementById("maskEditorCanvasStack"),
    maskEditorCanvas: document.getElementById("maskEditorCanvas"),
    maskSelectionCanvas: document.getElementById("maskSelectionCanvas"),
    maskGuideCanvas: document.getElementById("maskGuideCanvas"),
    maskTextCanvas: document.getElementById("maskTextCanvas"),
    maskEditorCursor: document.getElementById("maskEditorCursor"),
    maskPaintDirectionSection: document.getElementById("maskPaintDirectionSection"),
    maskBrushControlsSection: document.getElementById("maskBrushControlsSection"),
    maskBrushSize: document.getElementById("maskBrushSize"),
    maskBrushSizeValue: document.getElementById("maskBrushSizeValue"),
    btnMaskBrushSizeDown: document.getElementById("btnMaskBrushSizeDown"),
    btnMaskBrushSizeUp: document.getElementById("btnMaskBrushSizeUp"),
    maskBrushStrength: document.getElementById("maskBrushStrength"),
    maskBrushStrengthValue: document.getElementById("maskBrushStrengthValue"),
    btnMaskBrushStrengthDown: document.getElementById("btnMaskBrushStrengthDown"),
    btnMaskBrushStrengthUp: document.getElementById("btnMaskBrushStrengthUp"),
    maskBrushType: document.getElementById("maskBrushType"),
    maskActionHelp: document.getElementById("maskActionHelp"),
    maskSelectionActions: document.getElementById("maskSelectionActions"),
    btnMaskPolygonComplete: document.getElementById("btnMaskPolygonComplete"),
    btnMaskApplySelection: document.getElementById("btnMaskApplySelection"),
    btnMaskClearSelection: document.getElementById("btnMaskClearSelection"),
    maskPolygonPresetControls: document.getElementById("maskPolygonPresetControls"),
    maskPolygonPresetName: document.getElementById("maskPolygonPresetName"),
    maskPolygonPresetSelect: document.getElementById("maskPolygonPresetSelect"),
    maskPolygonPresetList: document.getElementById("maskPolygonPresetList"),
    btnSaveMaskPolygon: document.getElementById("btnSaveMaskPolygon"),
    btnLoadMaskPolygon: document.getElementById("btnLoadMaskPolygon"),
    btnDeleteMaskPolygon: document.getElementById("btnDeleteMaskPolygon"),
    btnMaskUndo: document.getElementById("btnMaskUndo"),
    btnMaskRedo: document.getElementById("btnMaskRedo"),
    btnMaskReset: document.getElementById("btnMaskReset"),
    btnMaskSkip: document.getElementById("btnMaskSkip"),
    btnMaskApply: document.getElementById("btnMaskApply"),
    maskEditorStatus: document.getElementById("maskEditorStatus"),
    maskTextEditorPanel: document.getElementById("maskTextEditorPanel"),
    maskTextLayerList: document.getElementById("maskTextLayerList"),
    maskTextInspector: document.getElementById("maskTextInspector"),
    btnMaskAddText: document.getElementById("btnMaskAddText"),
    btnMaskTextUp: document.getElementById("btnMaskTextUp"),
    btnMaskTextDown: document.getElementById("btnMaskTextDown"),
    btnMaskDuplicateText: document.getElementById("btnMaskDuplicateText"),
    btnMaskDeleteText: document.getElementById("btnMaskDeleteText"),
    maskTextContent: document.getElementById("maskTextContent"),
    maskTextFont: document.getElementById("maskTextFont"),
    maskTextSize: document.getElementById("maskTextSize"),
    maskTextColor: document.getElementById("maskTextColor"),
    maskTextOpacity: document.getElementById("maskTextOpacity"),
    maskTextX: document.getElementById("maskTextX"),
    maskTextY: document.getElementById("maskTextY"),
    maskTextWeight: document.getElementById("maskTextWeight"),
    maskTextAlign: document.getElementById("maskTextAlign"),
    maskTextRotation: document.getElementById("maskTextRotation"),
    maskTextScaleX: document.getElementById("maskTextScaleX"),
    maskTextScaleY: document.getElementById("maskTextScaleY"),
    maskTextShadowEnabled: document.getElementById("maskTextShadowEnabled"),
    maskTextShadowBlur: document.getElementById("maskTextShadowBlur"),
    maskTextShadowDistance: document.getElementById("maskTextShadowDistance"),
    maskTextShadowAngle: document.getElementById("maskTextShadowAngle"),
    maskTextShadowColor: document.getElementById("maskTextShadowColor"),
    maskTextShadowOpacity: document.getElementById("maskTextShadowOpacity"),
    imageEditorModal: document.getElementById("imageEditorModal"),
    imageEditorCanvas: document.getElementById("imageEditorCanvas"),
    imageEditorDrawingCanvas: document.getElementById("imageEditorDrawingCanvas"),
    imageEditorCanvasWrap: document.getElementById("imageEditorCanvasWrap"),
    imageEditorStage: document.getElementById("imageEditorStage"),
    imageEditorTextQuickControls: document.getElementById("imageEditorTextQuickControls"),
    btnQuickTextSmaller: document.getElementById("btnQuickTextSmaller"),
    btnQuickTextLarger: document.getElementById("btnQuickTextLarger"),
    btnQuickTextRotateLeft: document.getElementById("btnQuickTextRotateLeft"),
    btnQuickTextRotateRight: document.getElementById("btnQuickTextRotateRight"),
    quickTextSizeValue: document.getElementById("quickTextSizeValue"),
    quickTextRotationValue: document.getElementById("quickTextRotationValue"),
    imageEditorPresetName: document.getElementById("imageEditorPresetName"),
    imageAdjustmentControls: document.getElementById("imageAdjustmentControls"),
    imageEffectControls: document.getElementById("imageEffectControls"),
    imageEditorLayerList: document.getElementById("imageEditorLayerList"),
    btnEditorLayerTab: document.getElementById("btnEditorLayerTab"),
    btnEditorTextTab: document.getElementById("btnEditorTextTab"),
    btnEditorShapeTab: document.getElementById("btnEditorShapeTab"),
    editorLayerTabPanel: document.getElementById("editorLayerTabPanel"),
    editorTextTabPanel: document.getElementById("editorTextTabPanel"),
    editorShapeTabPanel: document.getElementById("editorShapeTabPanel"),
    shapeLayerInspector: document.getElementById("shapeLayerInspector"),
    editorShapeType: document.getElementById("editorShapeType"),
    editorShapeOpacity: document.getElementById("editorShapeOpacity"),
    editorShapeFillColor: document.getElementById("editorShapeFillColor"),
    editorShapeFillOpacity: document.getElementById("editorShapeFillOpacity"),
    editorShapeStrokeColor: document.getElementById("editorShapeStrokeColor"),
    editorShapeStrokeWidth: document.getElementById("editorShapeStrokeWidth"),
    editorShapeX: document.getElementById("editorShapeX"),
    editorShapeY: document.getElementById("editorShapeY"),
    editorShapeWidth: document.getElementById("editorShapeWidth"),
    editorShapeHeight: document.getElementById("editorShapeHeight"),
    editorShapeRotation: document.getElementById("editorShapeRotation"),
    editorCanvasBackgroundEnabled: document.getElementById("editorCanvasBackgroundEnabled"),
    editorCanvasBackgroundColor: document.getElementById("editorCanvasBackgroundColor"),
    editorCanvasBackgroundOpacity: document.getElementById("editorCanvasBackgroundOpacity"),
    editorCanvasBackgroundOpacityValue: document.getElementById("editorCanvasBackgroundOpacityValue"),
    btnAddImageLayer: document.getElementById("btnAddImageLayer"),
    btnPutImageInLayer: document.getElementById("btnPutImageInLayer"),
    btnPutFmaImageInLayer: document.getElementById("btnPutFmaImageInLayer"),
    btnPutTextInLayer: document.getElementById("btnPutTextInLayer"),
    btnPutColorInLayer: document.getElementById("btnPutColorInLayer"),
    imageLayerFileInput: document.getElementById("imageLayerFileInput"),
    imageEditorFmaPicker: document.getElementById("imageEditorFmaPicker"),
    imageEditorFmaPickerGrid: document.getElementById("imageEditorFmaPickerGrid"),
    imageEditorFmaPickerStatus: document.getElementById("imageEditorFmaPickerStatus"),
    btnCloseImageEditorFmaPicker: document.getElementById("btnCloseImageEditorFmaPicker"),
    btnCancelImageEditorFmaPicker: document.getElementById("btnCancelImageEditorFmaPicker"),
    btnApplyImageEditorFmaPicker: document.getElementById("btnApplyImageEditorFmaPicker"),
    imageLayerList: document.getElementById("imageLayerList"),
    imageLayerInspector: document.getElementById("imageLayerInspector"),
    imageLayerEmpty: document.getElementById("imageLayerEmpty"),
    btnImageLayerUp: document.getElementById("btnImageLayerUp"),
    btnImageLayerDown: document.getElementById("btnImageLayerDown"),
    btnDuplicateImageLayer: document.getElementById("btnDuplicateImageLayer"),
    btnDeleteImageLayer: document.getElementById("btnDeleteImageLayer"),
    imageLayerOpacity: document.getElementById("imageLayerOpacity"),
    imageLayerOpacityValue: document.getElementById("imageLayerOpacityValue"),
    imageLayerRotation: document.getElementById("imageLayerRotation"),
    imageLayerRotationValue: document.getElementById("imageLayerRotationValue"),
    imageLayerX: document.getElementById("imageLayerX"),
    imageLayerXValue: document.getElementById("imageLayerXValue"),
    imageLayerY: document.getElementById("imageLayerY"),
    imageLayerYValue: document.getElementById("imageLayerYValue"),
    imageLayerWidth: document.getElementById("imageLayerWidth"),
    imageLayerWidthValue: document.getElementById("imageLayerWidthValue"),
    imageLayerHeight: document.getElementById("imageLayerHeight"),
    imageLayerHeightValue: document.getElementById("imageLayerHeightValue"),
    fillLayerInspector: document.getElementById("fillLayerInspector"),
    fillLayerPreview: document.getElementById("fillLayerPreview"),
    fillLayerColorStartLabel: document.getElementById("fillLayerColorStartLabel"),
    fillLayerColorStart: document.getElementById("fillLayerColorStart"),
    fillLayerColorEndRow: document.getElementById("fillLayerColorEndRow"),
    fillLayerColorEnd: document.getElementById("fillLayerColorEnd"),
    fillLayerOpacity: document.getElementById("fillLayerOpacity"),
    fillLayerOpacityValue: document.getElementById("fillLayerOpacityValue"),
    fillLayerAngleRow: document.getElementById("fillLayerAngleRow"),
    fillLayerAngle: document.getElementById("fillLayerAngle"),
    fillLayerAngleValue: document.getElementById("fillLayerAngleValue"),
    btnPickFillColorStart: document.getElementById("btnPickFillColorStart"),
    btnPickFillColorEnd: document.getElementById("btnPickFillColorEnd"),
    btnSwapFillLayerColors: document.getElementById("btnSwapFillLayerColors"),
    fillLayerEyedropperStatus: document.getElementById("fillLayerEyedropperStatus"),
    btnCropImageLayer: document.getElementById("btnCropImageLayer"),
    btnBgRemoveImageLayer: document.getElementById("btnBgRemoveImageLayer"),
    btnDuplicateImageAlpha: document.getElementById("btnDuplicateImageAlpha"),
    btnDuplicateImageMask: document.getElementById("btnDuplicateImageMask"),
    baseImageLayerVisible: document.getElementById("baseImageLayerVisible"),
    baseImageLayerSelectable: document.getElementById("baseImageLayerSelectable"),
    baseImageLayerOpacity: document.getElementById("baseImageLayerOpacity"),
    baseImageLayerOpacityValue: document.getElementById("baseImageLayerOpacityValue"),
    btnDuplicateBaseLayer: document.getElementById("btnDuplicateBaseLayer"),
    btnDuplicateBaseAlpha: document.getElementById("btnDuplicateBaseAlpha"),
    btnDuplicateBaseMask: document.getElementById("btnDuplicateBaseMask"),
    textLayerInspector: document.getElementById("textLayerInspector"),
    textLayerEmpty: document.getElementById("textLayerEmpty"),
    imageEditorStatus: document.getElementById("imageEditorStatus"),
    btnImageEditorBypass: document.getElementById("btnImageEditorBypass"),
    btnImageEditorUndo: document.getElementById("btnImageEditorUndo"),
    btnImageEditorResetZoom: document.getElementById("btnImageEditorResetZoom"),
    imageEditorZoomValue: document.getElementById("imageEditorZoomValue"),
    btnExportImageEditorProject: document.getElementById("btnExportImageEditorProject"),
    btnImportImageEditorProject: document.getElementById("btnImportImageEditorProject"),
    imageEditorProjectFileInput: document.getElementById("imageEditorProjectFileInput"),
    btnImageEditorDrawingDone: document.getElementById("btnImageEditorDrawingDone"),
    imageEditorDrawingTip: document.getElementById("imageEditorDrawingTip"),
    imageEditorDrawingSize: document.getElementById("imageEditorDrawingSize"),
    imageEditorDrawingSizeValue: document.getElementById("imageEditorDrawingSizeValue"),
    imageEditorDrawingColor: document.getElementById("imageEditorDrawingColor"),
    imageEditorDrawingOpacity: document.getElementById("imageEditorDrawingOpacity"),
    imageEditorDrawingOpacityValue: document.getElementById("imageEditorDrawingOpacityValue"),
    imageEditorDrawingStatus: document.getElementById("imageEditorDrawingStatus"),
    imageEditorFontSize: document.getElementById("imageEditorFontSize"),
    imageEditorFontSizeValue: document.getElementById("imageEditorFontSizeValue"),
    btnImageEditorMagnet: document.getElementById("btnImageEditorMagnet"),
    btnImageEditorPanMode: document.getElementById("btnImageEditorPanMode"),
    btnImageEditorReset: document.getElementById("btnImageEditorReset"),
    btnImageEditorClose: document.getElementById("btnImageEditorClose"),
    btnResetImageAdjustments: document.getElementById("btnResetImageAdjustments"),
    btnAddTextLayer: document.getElementById("btnAddTextLayer"),
    btnMoveLayerUp: document.getElementById("btnMoveLayerUp"),
    btnMoveLayerDown: document.getElementById("btnMoveLayerDown"),
    btnDuplicateTextLayer: document.getElementById("btnDuplicateTextLayer"),
    btnDeleteTextLayer: document.getElementById("btnDeleteTextLayer"),
    btnImageEditorCancel: document.getElementById("btnImageEditorCancel"),
    btnImageEditorSave: document.getElementById("btnImageEditorSave"),
    imageEditorSaveChoice: document.getElementById("imageEditorSaveChoice"),
    btnImageEditorSaveBack: document.getElementById("btnImageEditorSaveBack"),
    btnImageEditorReplace: document.getElementById("btnImageEditorReplace"),
    btnImageEditorNew: document.getElementById("btnImageEditorNew"),
    editorTextContent: document.getElementById("editorTextContent"),
    editorTextFont: document.getElementById("editorTextFont"),
    editorTextSize: document.getElementById("editorTextSize"),
    editorTextColor: document.getElementById("editorTextColor"),
    editorTextOpacity: document.getElementById("editorTextOpacity"),
    editorTextX: document.getElementById("editorTextX"),
    editorTextY: document.getElementById("editorTextY"),
    editorTextWeight: document.getElementById("editorTextWeight"),
    editorTextAlign: document.getElementById("editorTextAlign"),
    editorTextRotation: document.getElementById("editorTextRotation"),
    editorTextScaleX: document.getElementById("editorTextScaleX"),
    editorTextScaleY: document.getElementById("editorTextScaleY"),
    editorTextShadowEnabled: document.getElementById("editorTextShadowEnabled"),
    editorTextShadowBlur: document.getElementById("editorTextShadowBlur"),
    editorTextShadowDistance: document.getElementById("editorTextShadowDistance"),
    editorTextShadowAngle: document.getElementById("editorTextShadowAngle"),
    editorTextShadowColor: document.getElementById("editorTextShadowColor"),
    editorTextShadowOpacity: document.getElementById("editorTextShadowOpacity"),
    btnOpenFontManager: document.getElementById("btnOpenFontManager"),
    fontManagerModal: document.getElementById("fontManagerModal"),
    btnCloseFontManager: document.getElementById("btnCloseFontManager"),
    btnLoadWindowsFonts: document.getElementById("btnLoadWindowsFonts"),
    btnAddFontFiles: document.getElementById("btnAddFontFiles"),
    fontFileInput: document.getElementById("fontFileInput"),
    fontManagerStatus: document.getElementById("fontManagerStatus"),
    defaultTextFont: document.getElementById("defaultTextFont"),
    defaultTextSize: document.getElementById("defaultTextSize"),
    defaultTextColor: document.getElementById("defaultTextColor"),
    defaultTextWeight: document.getElementById("defaultTextWeight"),
    defaultTextShadow: document.getElementById("defaultTextShadow"),
    btnSaveFontDefaults: document.getElementById("btnSaveFontDefaults"),
    aiJenaModal: document.getElementById("aiJenaModal"),
    aiJenaNotice: document.getElementById("aiJenaNotice"),
    btnAiJenaClose: document.getElementById("btnAiJenaClose"),
    btnAiJenaFontSmaller: document.getElementById("btnAiJenaFontSmaller"),
    btnAiJenaFontLarger: document.getElementById("btnAiJenaFontLarger"),
    aiJenaFontSizeValue: document.getElementById("aiJenaFontSizeValue"),
    aiJenaPoseLibrary: document.getElementById("aiJenaPoseLibrary"),
    aiJenaPoseCategory: document.getElementById("aiJenaPoseCategory"),
    aiJenaPosePreset: document.getElementById("aiJenaPosePreset"),
    aiJenaPoseCount: document.getElementById("aiJenaPoseCount"),
    btnApplyAiJenaPose: document.getElementById("btnApplyAiJenaPose"),
    aiJenaPoseManager: document.getElementById("aiJenaPoseManager"),
    aiJenaCustomPoseCategory: document.getElementById("aiJenaCustomPoseCategory"),
    aiJenaCustomPoseText: document.getElementById("aiJenaCustomPoseText"),
    btnAddAiJenaPose: document.getElementById("btnAddAiJenaPose"),
    btnDeleteAiJenaPose: document.getElementById("btnDeleteAiJenaPose"),
    btnExportAiJenaPoses: document.getElementById("btnExportAiJenaPoses"),
    btnImportAiJenaPoses: document.getElementById("btnImportAiJenaPoses"),
    aiJenaPoseFileInput: document.getElementById("aiJenaPoseFileInput"),
    aiJenaPoseManagerStatus: document.getElementById("aiJenaPoseManagerStatus"),
    aiJenaVideoOptions: document.getElementById("aiJenaVideoOptions"),
    aiJenaVideoModel: document.getElementById("aiJenaVideoModel"),
    aiJenaVideoAspect: document.getElementById("aiJenaVideoAspect"),
    aiJenaVideoDuration: document.getElementById("aiJenaVideoDuration"),
    aiJenaVideoUseSource: document.getElementById("aiJenaVideoUseSource"),
    aiJenaKeyStatus: document.getElementById("aiJenaKeyStatus"),
    aiJenaBrushControls: document.getElementById("aiJenaBrushControls"),
    aiJenaBrushSize: document.getElementById("aiJenaBrushSize"),
    aiJenaBrushSizeValue: document.getElementById("aiJenaBrushSizeValue"),
    aiJenaBrushOpacity: document.getElementById("aiJenaBrushOpacity"),
    aiJenaBrushOpacityValue: document.getElementById("aiJenaBrushOpacityValue"),
    aiJenaUseSelection: document.getElementById("aiJenaUseSelection"),
    btnClearAiJenaReferences: document.getElementById("btnClearAiJenaReferences"),
    aiJenaFmaPicker: document.getElementById("aiJenaFmaPicker"),
    aiJenaFmaPickerGrid: document.getElementById("aiJenaFmaPickerGrid"),
    aiJenaFmaPickerStatus: document.getElementById("aiJenaFmaPickerStatus"),
    btnCloseAiJenaFmaPicker: document.getElementById("btnCloseAiJenaFmaPicker"),
    btnCancelAiJenaFmaPicker: document.getElementById("btnCancelAiJenaFmaPicker"),
    btnApplyAiJenaFmaPicker: document.getElementById("btnApplyAiJenaFmaPicker"),
    aiJenaReferencePreview: document.getElementById("aiJenaReferencePreview"),
    aiJenaReferencePreviewDialog: document.getElementById("aiJenaReferencePreviewDialog"),
    aiJenaReferencePreviewHandle: document.getElementById("aiJenaReferencePreviewHandle"),
    aiJenaReferencePreviewTitle: document.getElementById("aiJenaReferencePreviewTitle"),
    aiJenaReferencePreviewName: document.getElementById("aiJenaReferencePreviewName"),
    aiJenaReferencePreviewImage: document.getElementById("aiJenaReferencePreviewImage"),
    btnCloseAiJenaReferencePreview: document.getElementById("btnCloseAiJenaReferencePreview"),
    aiJenaReferenceStorage: document.getElementById("aiJenaReferenceStorage"),
    aiJenaReferencePresetName: document.getElementById("aiJenaReferencePresetName"),
    aiJenaReferencePresetList: document.getElementById("aiJenaReferencePresetList"),
    aiJenaReferenceSqliteList: document.getElementById("aiJenaReferenceSqliteList"),
    aiJenaReferenceFileInput: document.getElementById("aiJenaReferenceFileInput"),
    btnExportAiJenaReferences: document.getElementById("btnExportAiJenaReferences"),
    btnImportAiJenaReferences: document.getElementById("btnImportAiJenaReferences"),
    btnSaveAiJenaReferencesDb: document.getElementById("btnSaveAiJenaReferencesDb"),
    btnLoadAiJenaReferencesDb: document.getElementById("btnLoadAiJenaReferencesDb"),
    btnDeleteAiJenaReferencesDb: document.getElementById("btnDeleteAiJenaReferencesDb"),
    btnSaveAiJenaReferencesSqlite: document.getElementById("btnSaveAiJenaReferencesSqlite"),
    btnLoadAiJenaReferencesSqlite: document.getElementById("btnLoadAiJenaReferencesSqlite"),
    aiJenaReferenceStorageStatus: document.getElementById("aiJenaReferenceStorageStatus"),
    btnAiJenaClosePolygon: document.getElementById("btnAiJenaClosePolygon"),
    aiJenaSelectionStatus: document.getElementById("aiJenaSelectionStatus"),
    btnAiJenaClearMask: document.getElementById("btnAiJenaClearMask"),
    aiJenaCanvas: document.getElementById("aiJenaCanvas"),
    aiJenaMaskCanvas: document.getElementById("aiJenaMaskCanvas"),
    aiJenaStage: document.getElementById("aiJenaStage"),
    aiJenaCanvasStack: document.getElementById("aiJenaCanvasStack"),
    btnAiJenaResetZoom: document.getElementById("btnAiJenaResetZoom"),
    aiJenaResultPreview: document.getElementById("aiJenaResultPreview"),
    aiJenaVideoPreview: document.getElementById("aiJenaVideoPreview"),
    aiJenaHistoryPanel: document.getElementById("aiJenaHistoryPanel"),
    aiJenaHistoryResizer: document.getElementById("aiJenaHistoryResizer"),
    aiJenaHistoryList: document.getElementById("aiJenaHistoryList"),
    aiJenaHistoryCount: document.getElementById("aiJenaHistoryCount"),
    btnClearAiJenaHistory: document.getElementById("btnClearAiJenaHistory"),
    btnSendAllAiJenaHistory: document.getElementById("btnSendAllAiJenaHistory"),
    aiJenaChatHistory: document.getElementById("aiJenaChatHistory"),
    aiJenaPrompt: document.getElementById("aiJenaPrompt"),
    aiJenaProgressText: document.getElementById("aiJenaProgressText"),
    aiJenaProgressBar: document.getElementById("aiJenaProgressBar"),
    aiJenaProgressPercent: document.getElementById("aiJenaProgressPercent"),
    btnStopAiJena: document.getElementById("btnStopAiJena"),
    btnRunAiJena: document.getElementById("btnRunAiJena"),
    btnRunAiJenaVideo: document.getElementById("btnRunAiJenaVideo"),
    btnDownloadAiJenaVideo: document.getElementById("btnDownloadAiJenaVideo"),
    btnAddAiJenaResult: document.getElementById("btnAddAiJenaResult"),
    aiJenaSaveChoice: document.getElementById("aiJenaSaveChoice"),
    btnAiJenaChoiceCancel: document.getElementById("btnAiJenaChoiceCancel"),
    btnAiJenaReplace: document.getElementById("btnAiJenaReplace"),
    btnAiJenaNew: document.getElementById("btnAiJenaNew"),
    externalAppButtons: document.getElementById("externalAppButtons"),
    btnOpenStoryApp: document.getElementById("btnOpenStoryApp"),
    btnOpenStoryHtmlApp: document.getElementById("btnOpenStoryHtmlApp"),
    btnOpenAuraApp: document.getElementById("btnOpenAuraApp"),
    btnOpenAuraGeminiApp: document.getElementById("btnOpenAuraGeminiApp"),
    btnOpenBackgroundGeminiApp: document.getElementById("btnOpenBackgroundGeminiApp"),
    btnOpenGeminiApp: document.getElementById("btnOpenGeminiApp"),
    btnOpenBgApp: document.getElementById("btnOpenBgApp"),
    externalAppModal: document.getElementById("externalAppModal"),
    externalAppDialog: document.getElementById("externalAppDialog"),
    externalAppFrame: document.getElementById("externalAppFrame"),
    externalAppTitle: document.getElementById("externalAppTitle"),
    externalAppDescription: document.getElementById("externalAppDescription"),
    externalAppStatus: document.getElementById("externalAppStatus"),
    externalAppProgress: document.getElementById("externalAppProgress"),
    externalAppProgressPercent: document.getElementById("externalAppProgressPercent"),
    externalAppProgressBar: document.getElementById("externalAppProgressBar"),
    externalAppTaskProgress: document.getElementById("externalAppTaskProgress"),
    externalAppTaskStatus: document.getElementById("externalAppTaskStatus"),
    externalAppTaskPercent: document.getElementById("externalAppTaskPercent"),
    externalAppTaskBar: document.getElementById("externalAppTaskBar"),
    externalAppImportHint: document.getElementById("externalAppImportHint"),
    btnDockExternalApp: document.getElementById("btnDockExternalApp"),
    btnMinimizeExternalApp: document.getElementById("btnMinimizeExternalApp"),
    btnReloadExternalApp: document.getElementById("btnReloadExternalApp"),
    btnCloseExternalApp: document.getElementById("btnCloseExternalApp"),
    btnImportExternalCurrent: document.getElementById("btnImportExternalCurrent"),
    btnImportExternalAll: document.getElementById("btnImportExternalAll"),
    externalAppFmaPicker: document.getElementById("externalAppFmaPicker"),
    externalAppFmaPickerGrid: document.getElementById("externalAppFmaPickerGrid"),
    externalAppFmaPickerStatus: document.getElementById("externalAppFmaPickerStatus"),
    btnCloseExternalAppFmaPicker: document.getElementById("btnCloseExternalAppFmaPicker"),
    btnCancelExternalAppFmaPicker: document.getElementById("btnCancelExternalAppFmaPicker"),
    btnApplyExternalAppFmaPicker: document.getElementById("btnApplyExternalAppFmaPicker")
};

function showLoading(title) {
    if (!dom.loadingOverlay) return;
    dom.loadingTitle.innerText = title || "Processing...";
    dom.progressBar.style.width = "0%";
    dom.progressPercent.innerText = "0%";
    dom.loadingOverlay.style.display = "flex";
}

function updateLoading(percent) {
    if (!dom.progressBar) return;
    const p = Math.round(percent);
    dom.progressBar.style.width = p + "%";
    dom.progressPercent.innerText = p + "%";
}

function hideLoading() {
    if (dom.loadingOverlay) dom.loadingOverlay.style.display = "none";
}

let backgroundImportHideTimer = null;

function showBackgroundImportProgress(title) {
    if (!dom.backgroundImportProgress) return;
    clearTimeout(backgroundImportHideTimer);
    dom.backgroundImportProgress.hidden = false;
    dom.backgroundImportProgress.classList.remove("is-complete", "is-error");
    dom.backgroundImportTitle.textContent = title || "갤러리에 추가하는 중…";
    dom.backgroundImportBar.style.width = "0%";
    dom.backgroundImportPercent.textContent = "0%";
}

function updateBackgroundImportProgress(percent, title) {
    if (!dom.backgroundImportProgress) return;
    const value = Math.max(0, Math.min(100, Math.round(Number(percent) || 0)));
    dom.backgroundImportProgress.hidden = false;
    if (title) dom.backgroundImportTitle.textContent = title;
    dom.backgroundImportBar.style.width = `${value}%`;
    dom.backgroundImportPercent.textContent = `${value}%`;
}

function finishBackgroundImportProgress(title, options = {}) {
    if (!dom.backgroundImportProgress) return;
    const isError = Boolean(options.error);
    updateBackgroundImportProgress(isError ? 0 : 100, title);
    dom.backgroundImportProgress.classList.toggle("is-complete", !isError);
    dom.backgroundImportProgress.classList.toggle("is-error", isError);
    clearTimeout(backgroundImportHideTimer);
    backgroundImportHideTimer = setTimeout(() => {
        dom.backgroundImportProgress.hidden = true;
    }, isError ? 4200 : 1800);
}

