const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const chat = fs.readFileSync(path.join(root, 'AI_App', 'aiChat', 'ai-chat.js'), 'utf8');
const app = fs.readFileSync(path.join(root, 'js', 'app.js'), 'utf8');
const css = fs.readFileSync(path.join(root, 'AI_App', 'aiChat', 'ai-chat.css'), 'utf8');

assert.match(chat, /id="ai-chat-document-write"/);
assert.match(chat, /id="ai-chat-document-write-mode"/);
assert.match(chat, /aria-label="문서에 작성"[\s\S]*?<span aria-hidden="true">📝<\/span>/);
assert.match(chat, /value="cursor" aria-label="현재 커서">←<\/option>/);
assert.match(chat, /value="document-end" aria-label="문서 맨 아래">↓<\/option>/);
assert.match(chat, /value="selection" hidden aria-label="선택 영역">↔<\/option>/);
assert.match(chat, /id="ai-chat-document-write-mode"[\s\S]*?id="ai-chat-sentence-only"/);
assert.match(chat, /id="ai-chat-sentence-only"[^>]*aria-label="문장으로만 작성"/);
assert.match(chat, /SENTENCE_ONLY_KEY/);
assert.match(chat, /state\.sentenceOnlyEnabled[\s\S]*?필수 문장형 출력 규칙/);
assert.match(chat, /function captureDocumentSelection/);
assert.match(chat, /selectionSnapshot: documentSelectionSnapshot/);
assert.match(chat, /replaceSelection: selectionWriteModeActive\(\)/);
assert.ok(chat.indexOf('id="ai-chat-internet-toggle"') < chat.indexOf('id="ai-chat-document-write"'));
assert.ok(chat.indexOf('id="ai-chat-document-write"') < chat.indexOf('id="ai-chat-academic-count-wrap"'));
assert.match(chat, /function visibleDocumentStreamAnswer/);
assert.match(chat, /finishDocumentWrite\(assistantMessage\.content, 'completed'\)/);
assert.match(chat, /outputTarget: documentWriteSession \? 'document' : 'chat'/);
assert.match(chat, /문서에 작성된 답변 · 기록 펼쳐보기/);
assert.match(app, /function beginAIChatDocumentWrite/);
assert.match(app, /captureDocumentSelection: function/);
assert.match(app, /선택 이후 문서가 변경되어 원래 영역을 안전하게 수정할 수 없습니다/);
assert.match(app, /status === 'error' && session\.replacedSelection \? session\.originalText : text/);
assert.match(app, /function followAIChatDocumentWrite/);
assert.match(app, /followAIChatDocumentWrite\(session\)/);
assert.match(app, /beginDocumentWrite: function/);
assert.match(app, /updateDocumentWrite: function/);
assert.match(app, /finishDocumentWrite: function/);
assert.match(css, /\.ai-chat-document-write-toggle/);
assert.match(css, /\.ai-chat-document-write-toggle input \{[^}]*width: 15px;[^}]*height: 15px;[^}]*accent-color: #14b8a6;/s);
assert.doesNotMatch(css, /\.ai-chat-document-write-toggle input \{[^}]*opacity: 0;/s);

console.log('AI Jena document write wiring verified.');
